### ISSUE TITLE
Image: 	index.docker.io/

### ISSUE THREAD

**Issue by Sthopeless** [KopfKrieg/watchtower#4]
Hi and thanks for sharing your version! 

I have installed and after updated my containers within Portainer I see below "Image:" everything starts with [index.docker.io/] and I can not update/edit the container within Portainer having this error
" The Docker registry for the index.docker.io/portainer/portainer:latest image is not registered inside Portainer, you will not be able to create a container. Please register that registry first."

Any lights on what I have wrong?

**Comment by KopfKrieg** [comment]
No idea, sorry. I'm sure I've seen a similar issue upstream, but I can't find it right now.

**Comment by KopfKrieg** [comment]
Update: I've merged a branch weeks ago that probably created the issue. I've reverted the changes I've done, please update to the latest image (either latest or v0.4.0). This should fix the issue :)
