### ISSUE TITLE
Error response from daemon

### ISSUE THREAD

**Issue by PabloSzx** [KopfKrieg/watchtower#5]
I'm getting this error right now consistently in every watchtower instance i have running.

Unable to update container ***_watchtower_1, err='Error response from daemon: Get https://registry-1.docker.io/v2/kopfkrieg/watchtower/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Akopfkrieg%2Fwatchtower%3Apull&service=registry.docker.io: net/http: TLS handshake timeout'. Proceeding to next.

EDIT: An hour later it has stopped

EDIT: Nevemind, still happens but much less frequently, it could be just a docker hub problem

**Comment by KopfKrieg** [comment]
> TLS handshake timeout

Yep, probably a problem of Docker Hub's network. I'm closing this issue, but feel free to open it again if the problem persists.
