### ISSUE TITLE
Add REST API 

### ISSUE THREAD

**Issue by aepetelin** [KopfKrieg/watchtower#6]
Hi, 
I would like to add a simple REST API to control update flow manually, like:  
        
    GET /v1/stale
    POST /v1/update/{container-name}

**Comment by KopfKrieg** [comment]
Hi, and sorry for the delay. In the past few days the original project got "re-activated" and is now maintained again (me as maintainer included), therefore this fork will no longer be under active maintenance.

Could you please reopen your issue here: https://github.com/containrrr/watchtower
